//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcialP3Entrega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mSTATU
    {
        public mSTATU()
        {
            this.USERS = new HashSet<USER>();
        }
    
        public int idStatus { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<USER> USERS { get; set; }
    }
}
